with obj_hero
{	
	trigger_spawn=false;
	state=states.spawn;
	speech_text=choose(
		"...",
		"my head...",
		"what now?",
		"ugh...",
		"damn this",
		"not again",
		"why me",
		"that's it",
		"?",
		"in pain",
		".-*meditating*-.",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		""
	);
	var _sentence_chance=irandom_range(0,100);
	if _sentence_chance>40
	{
		if global.story_progress==1 && global.deathcount==1
		{
			speech_text = choose(
				"...",
				"my head...",
				"ugh...",
				"?",
				"where\nam I",
				"what\nnow?",
				"I don't\nremember...",
				"what is\nthis place?",
				"stay\ncalm...",
				"I need\nto move",
			);
		}
		if global.story_progress>=2
		{
			speech_text = choose(
				"...",
				"my head...",
				"ugh...",
				"damn this",
				"not again",
				"why me",
				"that's it",
				"?",
				"broken\nrib",
				".-*meditating*-.",
				"still\nalive?",
				"not\nagain...",
				"same\ndream...",
				"ugh...",
				"fuck...",
				"they\nlied...",
				"this\nplace...",
				"everything\nhurts...",
				"my\nchest...",
				"deep\nbruise...",
				"still\nhere...",
				"again?",
				"how\nlong?",
				"cold\nagain...",
				"no\nchange...",
				"dark\neverywhere...",
				"the ground\nfeels familiar",
				"just\nbones...",
				"the\nvoid...",
				"no escape...",
				"how many\ntimes?",
				"pain is\nnormal...",
				"no\nprogress...",
				"am I\ndoing this?",
				"what's the\npoint...",
				"back\nagain...",
				"something's\nmissing...",
				"it\nhurts...",
				"familiar\ndirt...",
				"can't\ngo back...",
				"breathe...\nagain...",
				"why\nstill here?",
				"slipped\nback...",
				"another\nround...",
				"try\nagain...",
				"fail\nagain...",
				"who\ncares...",
				"head\nspinning...",
				"eyes\nburn...",
				"too\nfamiliar...",
				"already\nhere...",
				"again...",
				"step\none...",
				"how\ndo I leave?",
				"no\nrest...",
				"stuck\nagain...",
				"still\nnot free...",
				"wake\nwalk kill...",
				"no one\ncares...",
				"I'm not\nsurprised...",
				"no\nexit...",
				"not real...\nnot fake...",
				"they\nforget me...",
				"maybe\nthis time...",
				"don't\nhope...",
				"they know\nI'm awake...",
				"walk it\noff...",
				"stupid\ncycle...",
			);
		}
	}
}